import { StyleSheet } from "react-native";
import { colors } from "../constants/theme";

export const authSharedStyles = StyleSheet.create({
  formCard: {
    flex: 1,
    borderRadius: 0,
    borderWidth: 0,
    backgroundColor: colors.surface,
    overflow: "hidden",
  },
  heroOverlay: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: "rgba(117, 117, 117, 0.45)",
    height: "100%",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  heroTitle: {
    color: "#fff",
    fontSize: 32,
    fontWeight: "800",
    textAlign: "center",
  },
  heroSubtitle: {
    marginTop: 6,
    color: "#ffedd5",
    fontSize: 16,
    lineHeight: 20,
    textAlign: "center",
  },
  formBody: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 22,
    paddingBottom: 24,
    justifyContent: "flex-start",
  },
  pawIcon: {
    alignSelf: "center",
    marginBottom: 8,
    fontSize: 32,
  },
  title: {
    fontSize: 26,
    fontWeight: "700",
    color: colors.foreground,
    textAlign: "center",
  },
  description: {
    marginTop: 6,
    marginBottom: 14,
    fontSize: 12,
    lineHeight: 20,
    color: colors.muted,
    textAlign: "center",
  },
  input: {
    borderWidth: 1,
    borderColor: "#f97316",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 11,
    marginBottom: 10,
    backgroundColor: "#fff",
  },
  inputWrapper: {
    position: "relative",
    marginBottom: 10,
  },
  inputWithToggle: {
    borderWidth: 1,
    borderColor: "#f97316",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 11,
    paddingRight: 48,
    backgroundColor: "#fff",
  },
  toggleButton: {
    position: "absolute",
    right: 10,
    top: 8,
    paddingHorizontal: 6,
    paddingVertical: 4,
  },
  toggleText: {
    color: colors.brand600,
    fontWeight: "700",
    fontSize: 12,
  },
  button: {
    marginTop: 8,
    backgroundColor: colors.brand500,
    borderRadius: 12,
    alignItems: "center",
    paddingVertical: 13,
  },
  buttonText: {
    color: "#fff",
    fontWeight: "600",
  },
  helperText: {
    marginTop: 10,
    textAlign: "center",
    lineHeight: 21,
    color: colors.muted,
    fontWeight: "500",
  },
  helperHighlight: {
    color: colors.brand600,
    fontWeight: "700",
  },
});
